fix workflow

diff --git a/.github/workflows/vercel_build_test.yaml b/.github/workflows/vercel_build_test.yaml
--- a/.github/workflows/vercel_build_test.yaml
+++ b/.github/workflows/vercel_build_test.yaml
@@ -20,4 +20,31 @@ jobs:
         run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN
       
       - name: Build Project Artifacts
-        run: vercel build --prod --token=$VERCEL_TOKEN
+        id: build-test
+        run: vercel build --prod --token=$VERCEL_TOKEN | echo "BUILD_STATUS=$?" > "$GITHUB_OUTPUT"
+
+      - name: Create failed comment file
+        env: 
+          BUILD_STATUS: ${{ steps.build-test.outputs.BUILD_STATUS }}
+        if: $BUILD_STATUS != 0
+        run: |
+          cat  << EOF > comment.md
+          ## Test Failed
+          The tests failed. Please check the logs for more information.
+          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+          EOF
+
+      - name: Create success comment file
+        env: 
+          BUILD_STATUS: ${{ steps.build-test.outputs.BUILD_STATUS }}
+        if: $BUILD_STATUS == 0
+        run: |
+          cat  << EOF > comment.md
+          ## Test Success
+          The tests succeeded.
+          EOF
+
+      - name: Build failed comment
+        env: 
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: gh pr comment ${{github.event.number}} --body-file comment.md --edit-last || gh pr comment ${{ github.ref_name }} --body-file comment.md
